import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import { Toaster } from "sonner";

const cuteFont = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cuteFont.variable} antialiased`}>
        <Provider>{children}</Provider>
        <Toaster
          position="top-center"
          duration={3000}
          toastOptions={{
            style: {
              color: "#fff",
              fontWeight: 500,
            },
          }}
        />
      </body>
    </html>
  );
}
