import type { Metadata } from "next";
import { Cute_Font, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import { Toaster } from "sonner";

const cuteFont = Cute_Font({
  variable: "--font-cute", //src/global.css에서 사용될 변수명
  weight: "400",
  subsets: ["latin"], // 라틴 문자셋만 로드
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cuteFont.variable} antialiased`}>
        <Provider>{children}</Provider>
        <Toaster
          // position
          position="top-center"
          // duration : 3초
          duration={3000}
        />
      </body>
    </html>
  );
}
